### ISSUE TITLE
Not working inside custom docker-compose file

### ISSUE THREAD

**Issue by colthreepv** [kylemanna/docker-openvpn#147]
I'm creating a personal docker-compose service which inherits from this Image.

The idea of this compose file is to create an automatically built image, create server certificates without pass (y it's less secure), then attach to the (running) container via bash, manually create client certificates and ship them manually.

2 files only are involved:
`docker-compose.yml`
`Dockerfile`

`Dockerfile`:

``` dockerfile
FROM kylemanna/openvpn
ENV DEBUG=1

ENV OVPN_SERVER_URL="udp://awesome.site"
ENV OVPN_DEFROUTE=0
ENV OVPN_COMP_LZO=1

RUN ovpn_genconfig
RUN echo -e '\r' | ovpn_initpki nopass
```

`docker-compose.yml`

``` yaml
version: '2'
services:
  vpn:
    build: .
    ports:
      - '1194:1194/udp'
    volumes:
      - conf:/etc/openvpn
    cap_add:
      - NET_ADMIN

volumes:
  conf: {}
```

The step 7: ovpn_initpki crashes because the `ovpn_genconfig` doesn't create a config file correctly

Error Log:

```
Successfully generated config
 ---> ec750386fb55
Removing intermediate container 5e8cab299ef5
Step 7 : RUN echo -e '\r' | ovpn_initpki nopass
 ---> Running in fd085b38ed74
+ set -e
+ source /etc/openvpn/ovpn_env.sh
/usr/local/bin/ovpn_initpki: line 13: /etc/openvpn/ovpn_env.sh: No such file or directory
ERROR: Service 'vpn' failed to build: The command '/bin/sh -c echo -e '\r' | ovpn_initpki nopass' returned a non-zero code: 1
```

Any ideas how to fix this?

**EDIT**: I think it has something to do with `VOLUME ['/etc/openvpn']` in the original Dockerfile

**Comment by colthreepv** [comment]
As a followup, I found this is currently a bug on [docker#3639](https://github.com/docker/docker/issues/3639)

I suggest removing the `VOLUME ['/etc/openvpn']` until that is fixed

**Comment by kylemanna** [comment]
Thanks @colthreepv for tracking down the upstream bug.

I'd like to keep the volume so that user's data persists even if they forget it to pass it in on the command line.  Will wait for upstream fix to keep things simple on this repo.

**Comment by holms** [comment]
My version of docker-compose.yml

```
 openvpn-server:
     image: "kylemanna/openvpn"
     ports:
         - "1194:1194/udp"
     cap_add:
         - NET_ADMIN
     volumes:
         - ovpn-data:/etc/openvpn
volumes:
    ovpn-data:
        driver: local

```

Works for me. Now for `docker-run` we do `docker-compose run`:

```
        docker-compose run --rm openvpn-server ovpn_genconfig -u udp://vpn.yourdomain.com
        docker-compose run --rm openvpn-server ovpn_initpki
        docker-compose run --rm openvpn-server easyrsa build-client-full yourdomain.com nopass
        docker-compose run --rm openvpn-server ovpn_getclient yourdomain.com > yourdomain.com.ovpn
```
