### ISSUE TITLE
"packet HMAC authentication failed" on Docker Cloud hosted on Azure

### ISSUE THREAD

**Issue by razvanmitre** [kylemanna/docker-openvpn#167]
Hello,

I am trying to setup an OpenVPN server on Docker Cloud hosted on Azure.

The problem is that when I try to connect with a client on the VPN server it gives this error:

```
TLS Error: incoming packet authentication failed from [AF_INET] ip:1025 
Authenticate/Decrypt packet error: packet HMAC authentication failed
```

This error also appears immediately after initialization, in that case ip is the server's ip. So I think that not even the server can connect to itself.

I am using this docker image: https://hub.docker.com/r/aestheticworks/openvpn-server-public
from this git repo https://bitbucket.org/aesthetic/openvpn-server-public/src

I am using kylemanna/openvpn with some custom scripts, but nothing that changes the functionality.

The stack file on Docker Cloud is:

```
openvpn:
  cap_add:
    - NET_ADMIN
  image: 'aestheticworks/openvpn-server-public:latest'
  ports:
    - '1194:1194/udp'
  restart: always
  volumes:
    - /etc/openvpn
```

I have tried this exact configuration on a standard EC2 instance, with docker-compose and it works.

Does anyone know why it is not working on Docker Cloud?

Thanks.
