### ISSUE TITLE
Certificate expiration time

### ISSUE THREAD

**Issue by Ape** [kylemanna/docker-openvpn#453]
If I understood correctly the server and client certificates expire after 10 years from creation. Is there a way to set the expiration time to like 100 years or completely disable the expiration?

I know that 10 years is a rather long time, but it is still short enough that it might cause issues.

**Comment by buchdag** [comment]
> Is there a way to set the expiration time to like 100 years

Yes, if you set the relevant [Easy RSA environment variables](https://github.com/pivpn/easy-rsa/blob/master/doc/EasyRSA-Advanced.md#environmental-variables-reference) on the container to bypass the default values:

```
docker run \
    -v $OVPN_DATA:/etc/openvpn \
    --log-driver=none \
    --env EASYRSA_CA_EXPIRE=36500 \
    --env EASYRSA_CERT_EXPIRE=36500 \
    --env EASYRSA_CRL_DAYS=36500 \
    --rm -it kylemanna/openvpn ovpn_initpki
```

Then don't forget to supply the `EASYRSA_CERT_EXPIRE` variable each time you generate a client certificate and the `EASYRSA_CRL_DAYS` variable each time you revoke a client certificate.

You can also put those variables in a file mounted at `/etc/openvpn/vars`, the container will read them automatically.

> or completely disable the expiration?

Nope.

Please note that I have no idea of the issues that might or might nor arise from setting expiration dates that far into the future.

**Comment by Ape** [comment]
Thanks.

**Comment by VictorKrasnov** [comment]
docker-compose.yml example: 

```
version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
    environment:
    - EASYRSA_CA_EXPIRE=36500
    - EASYRSA_CERT_EXPIRE=36500
    - EASYRSA_CRL_DAYS=36500
```
