### ISSUE TITLE
How can I get OpenVPN to use my PiHole container as the DNS server?

### ISSUE THREAD

**Issue by FutureTense** [kylemanna/docker-openvpn#457]
I have a PiHole container providing DNS for my network.  It provides some static DNS entries as well as ad-blocking.

When I connect via OpenVPN, how can I get OpenVPN to only use PiHole for DNS?  Here is the docker-compose I use for PiHole

```
  pihole:
    container_name: pihole
    domainname: docker
    hostname: pihole
    image: pihole/pihole:4.2.1
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 1969:80
      - 8183:443
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ${USERDIR}/docker/pihole/pihole:/etc/pihole
      - ${USERDIR}/docker/pihole/dnsmasq.d:/etc/dnsmasq.d
    extra_hosts:
      - foo:172.16.68.6
      - bar:172.16.68.7
      - fubar:172.16.68.9
      - foobar:172.16.68.40
    environment:
      - ServerIP=${SERVER_IP}
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=pihole.${DOMAINNAME}
      - VIRTUAL_PORT=80
      - TZ=${TZ}
      - WEBPASSWORD=${PIHOLE_PASSWORD}
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1

```

Alternatively, how can I manually have OpenVPN just point to two ip addresses?

**Comment by mr-bolle** [comment]
Hi, have a look on this repository [docker-openvpn-pihole](http://github.com/mr-bolle/docker-openvpn-pihole).
I prepare a openvpn-install script, this set the static dns ip from pihole container into your openvpn server configuration.

**Comment by sam2kb** [comment]
Here's an excerpt from a well tested config

`PIHOLE_IP=172.18.0.3`

```
docker run --rm \
  -v /some/dir/openvpn:/etc/openvpn \
  kylemanna/openvpn ovpn_genconfig \
  -u udp://${VPN_IP} \
  -n ${PIHOLE_IP} \
```
Add a fixed IP address to pihole config

```
pihole:
  image: pihole/pihole
  networks:
    private:
      ipv4_address: ${PIHOLE_IP}
```

**Comment by FutureTense** [comment]
@sam2kb 

What is the -n option for docker run?  I'm trying to find the equivalent for docker-compose

Here is mine

```
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ${USERDIR}/docker/openvpn-data/conf:/etc/openvpn
```

Also, I don't have a "private" network defined, so I'm not sure what to do.

Here is what I do have defined in my docker-compose:

```
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
```

And if I use **default** I get the following:

> ERROR: for pihole  Cannot start service pihole: Invalid address 172.16.68.62: It does not belong to any of this network's subnets
>ERROR: Encountered errors while bringing up the project.

**Comment by mr-bolle** [comment]
With `-n` you can set the DNS Server for your OpenVPN Server

https://github.com/kylemanna/docker-openvpn/blob/master/bin/ovpn_genconfig

**Comment by FutureTense** [comment]
The IP of my docker server that is already running PiHole is 172.16.68.62.  I modified the call for **ovpn_genconfig** to as follows:

```
PIHOLE_IP="172.16.68.62"
docker run -v $OVPN_DATA:/etc/openvpn --log-driver=none --rm kylemanna/openvpn ovpn_genconfig -u udp://vpn.${VPN_CLIENT_NAME} -n ${PIHOLE_IP}
```

Anytime I try to use https://github.com/mr-bolle/docker-openvpn-pihole, nothing seems to work.   I continually get the following error:

> ERROR: for vpn_openvpn  user specified IP address is supported only when connecting to networks with user configured subnet

**Comment by mr-bolle** [comment]
If you use your sub-network you have to adjust the openvpn IP, it is necessary that both container can speak together.



docker-compose.yml
```
openvpn:
networks:
vpn-network:
ipv4_address: 172.16.68.61

pihole:
networks:
vpn-network:
ipv4_address: 172.16.68.62

networks:
vpn-network:
external: true
```
To create this new sub-network 

`docker network create --driver=bridge --subnet=172.16.68.0/24 --gateway=172.16.68.1 vpn-network`

**Comment by FutureTense** [comment]
Figured it out.  I changed my docker compose per below.  This lets openvpn see pihole.  The default network is necessary to allow pihole to be accessible as it was before on the network.

```
    pihole:
    networks:
      pihole_sub:
        ipv4_address: 172.68.0.2
      default:

    openvpn:
    networks:
      pihole_sub:

  pihole_sub:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.68.0.0/16
```

So start your docker compose stack, then populate the ip and client name as follows:
```
PIHOLE_IP=$(docker inspect --format '{{ .NetworkSettings.Networks.docker_pihole_sub.IPAddress }}' $(docker ps -aqf "name=pihole"))
VPN_CLIENT_NAME="example.com"
```

Initialize your docker volume to use your static IP for your pihole_sub network
```
docker run -v ${USERDIR}/docker/openvpn:/etc/openvpn --log-driver=none --rm kylemanna/openvpn ovpn_genconfig -u udp://vpn.${VPN_CLIENT_NAME} -n ${PIHOLE_IP}
```
And then generate your OpenVPN server stuff
```
docker run -v ${USERDIR}/docker/openvpn:/etc/openvpn --log-driver=none --rm -it kylemanna/openvpn ovpn_initpki
```
At this point restart or rebuild the OpenVPN container.  Now you can generate and retrieve client ovpn files:

```
#Generate a client certificate without a passphrase
docker run -v ${USERDIR}/docker/openvpn:/etc/openvpn --log-driver=none --rm -it kylemanna/openvpn easyrsa build-client-full ${VPN_CLIENT_NAME} nopass

#Retrieve the client configuration with embedded certificates
docker run -v ${USERDIR}/docker/openvpn:/etc/openvpn --log-driver=none --rm kylemanna/openvpn ovpn_getclient ${VPN_CLIENT_NAME} > ${VPN_CLIENT_NAME}.ovpn
```

If for some reason you need to change the static IP for PiHole, you just need to put these values in **ovpn_env.sh** and **openvpn.conf** and restart the openvpn container.  Now your OpenVPN clients will be just like your clients inside your network.  They will have access to network resources, use PiHole ad blocking, and will have DNS routing to entries defined in PiHole’s “extra hosts” section.
