### ISSUE TITLE
Can't route all traffic through VPN

### ISSUE THREAD

**Issue by ruippeixotog** [kylemanna/docker-openvpn#638]
I want to migrate my existing OpenVPN install to use this Docker container but I'm having some trouble finding the right settings so that it can route all Internet traffic through the VPN.

I'm trying to set an OpenVPN instance with the following setup:

- Using TCP
- VPN internal network should be 10.9.0.0/24
- VPN clients should be able machines in the host network 192.168.1.0/24
- VPN clients should be able to tunnel Internet traffic through the VPN

In order to build a config for this, I configuring the following service in my docker-compose.yml file:

```yml
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - $MY_HOST_CONF_DIR:/etc/openvpn
    ports:
      - 1194:1194
```

And I ran the following commands:

```bash
$ docker-compose run --rm openvpn ovpn_genconfig -N -d -u tcp://$MY_DNS -s 10.9.0.0/24 -p "route 192.168.1.0 255.255.255.0"

$ docker-compose run --rm openvpn ovpn_initpki
$ docker-compose run --rm openvpn easyrsa build-client-full $MY_CLIENT nopass

$ docker-compose run --rm openvpn ovpn_getclient $MY_CLIENT > $MY_CLIENT.ovpn
```

I'm now trying to connect to connect with Tunnelblick. If I connect with the "Route all IPv4 traffic through the VPN" option I can't reach either 192.168.9.0/24 addresses nor Internet addresses. If I connect without this option I can access 192.168.9.0/24 addresses.

I'm not an expert in networking or OpenVPN configuration, so I may be missing something obvious. What am I doing wrong?
