### ISSUE TITLE
please update complete image is uses old packages which are not secure any more

### ISSUE THREAD

**Issue by travelg** [kylemanna/docker-openvpn#667]
Please update all base image and packages to latest, which resolved many security loop holes.

Please update for amd64 and also for aarch64. thanks

**Comment by JellevanKraaij** [comment]
Yes i love this image, the best so far i know. How can we help to update/rebuild this image with the latest openvpn version?
Thanks alot!

**Comment by FarisZR** [comment]
pull the repository and then build the image manually.
it worked for me and now its using openvpn v 2.5.2, even though the latest is 2.5.3 but i guess alpine have yet to update their package.

## docker-compose example:
clone the repo to the same file where the compose config is located
```
version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
#    image: kylemanna/openvpn
    build:
      context: ./docker-openvpn
      dockerfile: ./Dockerfile
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
```

and then `docker-compose build --pull `(V1) or `docker compose build --pull` (V2)
and then run the project normally with docker-compose/docker compose up -d
