### ISSUE TITLE
Port not open

### ISSUE THREAD

**Issue by parsanoori** [kylemanna/docker-openvpn#713]
I have the following on `docker ps`:
```
CONTAINER ID   IMAGE                                  COMMAND                  CREATED              STATUS          PORTS                                                                                  NAMES
004d431e4cdf   kylemanna/openvpn:2.4                  "ovpn_run"               About a minute ago   Up 26 seconds   0.0.0.0:1194->1194/udp, :::1194->1194/udp                                              openvpn_ovpn_1
```
I have the following configs on my `docker-compose.yml`:
```
version: "3"
services:
  ovpn:
    image: kylemanna/openvpn:2.4
    restart: always
    volumes:
      - ./ovpn-data:/etc/openvpn:rw
    ports:
      - 1194:1194/udp
    cap_add:
      - NET_ADMIN
```
But when I run `ss -tolnp` there's no port 1194, neither on ipv4 nor on ipv6.
